// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_wmavxFYWs5nAdCDiFBZlAzcL4wYLeig',
    appId: '1:919926666177:web:cd90b3aa555200eaddf540',
    messagingSenderId: '919926666177',
    projectId: 'new-chats-37c0e',
    authDomain: 'new-chats-37c0e.firebaseapp.com',
    storageBucket: 'new-chats-37c0e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDIbwPIUPmpsI_vRAa1HOEudlHq1RMKhE',
    appId: '1:919926666177:android:1d6b842977d79e42ddf540',
    messagingSenderId: '919926666177',
    projectId: 'new-chats-37c0e',
    storageBucket: 'new-chats-37c0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5TunV7HXXUkl9Q-UbijYrpa7RX14LGBk',
    appId: '1:919926666177:ios:b60823c3fd5c2835ddf540',
    messagingSenderId: '919926666177',
    projectId: 'new-chats-37c0e',
    storageBucket: 'new-chats-37c0e.appspot.com',
    iosClientId: '919926666177-gfrcgnmclt451kle4ocvd1n53ftt7qqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5TunV7HXXUkl9Q-UbijYrpa7RX14LGBk',
    appId: '1:919926666177:ios:570a547a6e67f9fcddf540',
    messagingSenderId: '919926666177',
    projectId: 'new-chats-37c0e',
    storageBucket: 'new-chats-37c0e.appspot.com',
    iosClientId: '919926666177-p60vd95icbn6k45cp9ttlhedc1vm1868.apps.googleusercontent.com',
    iosBundleId: 'com.example.chats.RunnerTests',
  );
}
